[package]
name = "unique-types"
version = "0.1.0"
edition = "2021"

[features]

default = ["std"]

std = ["alloc", "dep:rustc-hash", "exclusion-set?/std"]
alloc = []

[dependencies.rustc-hash]
version = "2.0"
optional = true

[dependencies.exclusion-set]
version = "0.1"
optional = true
